In [2]:
import os
import time
import tqdm
import itertools
import numpy as np
import scipy.sparse as sparse
import scipy.sparse.linalg

In [2]:
X = np.array([[0, 1],[1, 0]], dtype=int)
Z = np.array([[1, 0], [0, -1]], dtype=int)
I = np.array([[1, 0], [0, 1]])
II = sparse.dia_matrix((np.ones(2), np.array([0])), dtype=int, shape=(2, 2))

In [3]:
def read_eigenvectors(file):
    with open(file, 'r+') as f:
        text_data = f.readlines()

        h_vals = []
        for i in range(len(text_data)):
            h1h2, eigenvector = text_data[i].split("_")

            h_vals.append(tuple(map(float, h1h2[1: -1].split(", "))))
            text_data[i] = eigenvector
        
        return h_vals, np.loadtxt(text_data, dtype=complex)

In [4]:
def find_kron(array, index, q_bits):
    order = np.ones(q_bits)
    order[index-1] = 0
    assert index <= q_bits
    t = sparse.dia_matrix((pow(2, q_bits), pow(2, q_bits)), dtype=int)

    for i in range(1, len(order)):
        current = array if order[i] == 0 else II

        if i == 1:
            t = array if order[i-1] == 0 else II

        t = sparse.kron(t, current)

    return t.copy()

In [5]:
# third_term = np.zeros(shape=(pow(2, 4), pow(2, 4)), dtype=float)

# for i in range(4-1):
#     elem = i + 1
#     print(f"third term {elem}/3")

#     b1 = find_kron(X, elem, 4)
#     b2 = find_kron(X, elem+1, 4)
#     b1_rows, _ = sparse.coo_matrix

In [27]:
n=2
third_term = np.zeros(shape=(pow(2, n), pow(2, n)), dtype=float)

elem = 1
b1 = find_kron(X, elem, n)
b2 = find_kron(X, elem+1, n)
# b1_rows, _ = sparse.coo_matrix(b1, dtype=sparse.coo_matrix).nonzero()      #行列b1の1が存在する行のindexをb1_rowsに格納
# _, b2_cols = sparse.coo_matrix(b2, dtype=sparse.coo_matrix).nonzero()      #行列b2の1が存在する列のindexをb2_rowsに格納

b1 = np.array([[0, 0, 1, 0],
               [0, 0, 0, 1],
               [1, 0, 0, 0],
               [0, 1, 0, 0]])
b2 = np.array([[0 1 0 0]
               [1 0 0 0]
               [0 0 0 1]
               [0 0 1 0]])

b1_rows, b1_cols = sparse.coo_matrix(b1, dtype=sparse.coo_matrix).nonzero()
b2_rows, wrongly_ordered_b2_cols = b1_cols, []

def extract_elem(elem):
    wrongly_ordered_b2_cols.append(elem)

list(map(b2.getrow, filter(extract_elem, b2_rows)))

# b2_cols = []
# swaps = int(pow(2, n-1-elem))
# groups = [wrongly_ordered_b2_cols[i:i + swaps] for i in range(0, len(wrongly_ordered_b2_cols), swaps)]

# for j in range(int(len(groups) / 2)):
#     switch = groups[2 * j: (2 * j) + 2]
#     b2_cols.append([*switch[1], *switch[0]])

# b2_cols = list(itertools.chain(*b2_cols))

# combined = sparse.coo_matrix((np.ones(pow(2, n), dtype=int), (b1_rows, b2_cols)),
#                              shape=(pow(2, n), pow(2, n)))


# third_term -= combined.toarray()
# print(third_term)


<bound method spmatrix.getrow of <4x4 sparse matrix of type '<class 'numpy.int32'>'
	with 8 stored elements (blocksize = 2x2) in Block Sparse Row format>>
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [29]:
II = sparse.dia_matrix((np.ones(2), np.array([0])), dtype=int, shape=(2, 2))
Z = sparse.dia_matrix((np.array([1, -1]), np.array([0])), dtype=int, shape=(2, 2))
X = sparse.dia_matrix((np.array([2]), np.array([-1])), dtype=int, shape=(2, 2))
X.setdiag(np.ones(1), 1)


ma = X
print(ma.toarray())
np.array([np.ones(1)])

[[0 1]
 [2 0]]


array([[1.]])